### Options
OPTIONS http://localhost:1337/

### Health Check
GET http://localhost:1337/healthcheck 

### Health Post Check
POST http://localhost:1337/healthcheck 
content-type: application/json

{
    "name": "sample",
    "email": "elweiss01@gmail.com"
} 


### Create User Pass
POST http://localhost:1337/users/create
Content-Type: application/json

{
    "email": "elweiss07@gmail.com",
    "role": ["admin"]
}

### Create User Fail
POST http://localhost:1337/users/create
Content-Type: application/json

{
    "email": "elweiss07",
    "role": ["admin"]
}


### Get User By Id
GET http://localhost:1337/users/get/667c31cbc3c1cebc2082a89a

### Delete User By Id
DELETE http://localhost:1337/users/delete/667c31cbc3c1cebc2082a89a

### Users Query
POST http://localhost:1337/users/query
Content-Type: application/json

{
    "email": "elweiss05@gmail.com"
}

### Update User Pass
PATCH http://localhost:1337/users/update/667c31cbc3c1cebc2082a89a
Content-Type: application/json

{

    "role": ["user"]
}
